### ISSUE TITLE
Add earnings to charts

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Sideways#20]

**Comment by tbrown747** [comment]
* show future estimated earnings dates ($)
* show earnings values:
** EPS ($)
** EPS beat vs estimates (%, happy sad colors)
** Revenue ($)
** Revenue beat vs estimates (%, happy sad colors)
* show trends [advanced (maybe new issue)]
** EPS vs last quarter and year over year (%)
** Revenue vs last quarter and year over year (%)

For positive to negative or negative to positive comparisons, use '#' to indicate absolute value

**Comment by JohanLarsson** [comment]
Closing this now, we open new issues for future tweaks.

![image](https://user-images.githubusercontent.com/1640096/123076215-339b0380-d419-11eb-84d6-e162fdf755b5.png)
