### ISSUE TITLE
Bookmarks Should Use Best Precision

### ISSUE THREAD

**Issue by tbrown747** [JohanLarsson/Sideways#38]
Bookmarks should use the precision of the right-hand (intraday) chart, e.g. if 1m is selected, the bookmark would be stored/recalled using the minute at the right-hand side of the right-hand chart. Current behavior stores the bookmark at the end of the current day bar regardless of the position of the intraday chart when the bookmark is stored.

**Comment by JohanLarsson** [comment]
Ew, that is bad, wonder how that happened, thanks for reporting.

**Comment by JohanLarsson** [comment]
The bug was in opening the bookmarks.
Changed it so that chart opens at bookmark position if offset is 0.
