### ISSUE TITLE
Remove $ETHE

### ISSUE THREAD

**Issue by izzeww** [JohanLarsson/Sideways#7]
![image](https://user-images.githubusercontent.com/9016665/118374390-2427cf80-b5bc-11eb-9ee8-92f24e29c7df.png)

Ticker ETHE (Grayscale Ethereum Trust) only has 1d data (no minute data) with AlphaVantage because it's listed on Pink Sheets/OTC market. Could be fixed by removing it from the list.

**Comment by JohanLarsson** [comment]
I think we build a database with specialcases like this. Keep reporting as you find them.

**Comment by JohanLarsson** [comment]
The downloader learns about symbols and creates an exclusion list in sideways.cfg

```json
{
  "AlphaVantage": {
    "ClientSettings": ...,
    "SymbolsWithMissingMinutes": [
      "ETHE",
      ...
}
```

Symbols are added to this list if download returns empty result.
