### ISSUE TITLE
Flash Screen / Play Sound when duplicate bookmark is attempted

### ISSUE THREAD

**Issue by tbrown747** [JohanLarsson/Sideways#71]
When the user attempts to create a bookmark where one already exists, the current behavior is to pop up a messagebox with a warning that must be acknowledged to proceed.

Instead, the application should lightly flash the screen and/or play a system sound to let the user know that the bookmark wasn't created, without required them to further acknowledge it.

**Comment by JohanLarsson** [comment]
Playing System.Beep now, perhaps not clear for user but does not break flow as much.
